name: vocabulary-cd

on:
  release:
    types:
    - published

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.16.1'

    - name: Install dependencies
      run: npm install --no-audit

    - name: Run build
      run: npm run build

    - name: Publish package
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
